from __future__ import annotations

from pathlib import Path
from typing import Mapping

from .analysis.tactical import build_tactical_analysis_report
from .backup_restore import backup_reliability_data, restore_reliability_data
from .engine.chart import build_election_report, build_snapshot
from .evidence_binder import build_evidence_binder, calculate_evidence_coverage, detect_cross_document_conflicts, detect_cross_document_support, detect_weak_or_stale_sources, format_evidence_binder_report_text, get_evidence_binder_summary, get_or_create_source_reliability, group_citations_for_proposal, load_evidence_binder, score_citation_bundle_strength, update_source_reliability_metadata
from .document_preflight import can_extract_after_preflight, format_preflight_report_text, get_document_preflight_summary, list_document_preflights, load_document_preflight, run_document_preflight
from .document_manifest import (
    build_document_manifest,
    format_document_manifest_report,
    get_document_backend_readiness,
    load_document_manifest,
    reconcile_document_subsystems,
    validate_source_locator,
)
from .document_content_map import (
    build_document_content_map,
    build_document_scoped_fingerprint,
    find_related_document_content,
    format_document_content_map_report,
    get_reader_backend_readiness,
    validate_document_provenance_contract,
)
from .document_content_curation import (
    build_curated_document_content_map,
    build_document_content_curation_workspace,
    format_document_content_curation_report,
    get_document_content_curation_summary,
    get_document_content_curation_readiness,
    load_document_content_curation,
    save_document_content_curation_change,
    validate_content_curation_change,
)
from .document_content_history import (
    compare_document_content_curation_revisions,
    format_document_content_curation_comparison_report,
    format_document_content_curation_history_report,
    format_document_content_curation_restore_report,
    list_document_content_curation_revisions,
    load_document_content_curation_revision,
    restore_document_content_curation_revision,
    validate_historical_curation_revision,
)
from .document_content_rebase import (
    abandon_document_content_rebase_workspace,
    apply_document_content_rebase_resolution,
    build_document_content_rebase_proposed_overlay,
    commit_document_content_rebase_workspace,
    create_rebase_workspace_from_current_stale_curation,
    create_rebase_workspace_from_historical_revision,
    format_document_content_rebase_report,
    get_document_content_rebase_readiness,
    list_document_content_rebase_workspaces,
    load_document_content_rebase_workspace,
    refresh_document_content_rebase_conflicts,
)
from .document_content_bulk import (
    add_document_content_bulk_operation,
    approve_document_content_bulk_plan,
    clear_document_content_bulk_operations,
    commit_document_content_bulk_plan,
    create_document_content_bulk_plan,
    format_document_content_bulk_report,
    list_document_content_bulk_plans,
    list_document_content_bulk_review_queue,
    load_document_content_bulk_plan,
    preview_document_content_bulk_plan,
    refresh_document_content_bulk_plan,
    reject_document_content_bulk_plan,
    remove_document_content_bulk_operation,
    replace_document_content_bulk_operation,
    validate_document_content_bulk_plan,
)
from .document_content_integrity import (
    abandon_document_content_transaction,
    apply_document_content_recovery_plan,
    create_document_content_recovery_plan,
    format_document_content_integrity_report,
    format_document_content_recovery_report,
    format_document_content_transaction_report,
    get_document_content_transaction_status,
    list_document_content_transactions,
    load_document_content_recovery_plan,
    load_document_content_transaction,
    rebuild_document_content_indexes,
    scan_document_content_integrity,
)
from .backend_contract_validation import (
    build_backend_contract_validation_plan,
    format_backend_contract_validation_report,
    get_backend_contract_validation_health,
    load_backend_contract_validation,
    run_backend_contract_validation,
)
from .pdf_viewport import (
    create_pdf_viewport_session,
    format_pdf_viewport_report,
    navigate_pdf_viewport,
    render_pdf_viewport_page,
    synchronize_pdf_viewport_to_locator,
)
from .pdf_text_layer import (
    build_pdf_highlight_overlay,
    extract_pdf_page_text_layer,
    format_pdf_text_layer_report,
    map_pdf_locator_to_rectangles,
    select_pdf_text_in_rectangle,
)
from .pdf_reader_workspace import (
    create_pdf_reader_workspace,
    draft_citation_from_pdf_selection,
    format_pdf_reader_workspace_report,
    save_pdf_reader_annotation,
    save_pdf_reader_bookmark,
)
from .citation_draft_review import (
    build_citation_draft_review_workspace,
    create_citation_from_approved_draft,
    format_citation_draft_review_report,
    get_citation_draft_review_health,
    save_citation_draft_review_decision,
)
from .evidence_handoff_review import (
    build_evidence_handoff_review_workspace,
    create_proposal_draft_from_evidence_handoff,
    format_evidence_handoff_review_report,
    insert_handoff_citation_into_binder,
    save_evidence_handoff_review_decision,
)
from .proposal_promotion import (
    build_proposal_promotion_workspace,
    format_proposal_promotion_report,
    get_proposal_promotion_health,
    promote_approved_proposal,
    save_proposal_promotion_decision,
)
from .proposal_rule_activation import (
    activate_rule_from_promoted_proposal,
    build_proposal_rule_activation_workspace,
    format_proposal_rule_activation_report,
    rollback_proposal_rule_activation,
    save_proposal_rule_activation_decision,
)
from .rule_activation_revalidation import (
    build_rule_activation_revalidation_workspace,
    complete_rule_activation_revalidation,
    format_rule_activation_revalidation_report,
    run_rule_runtime_contract_validation,
    save_rule_activation_revalidation_decision,
)
from .topic_taxonomy import (
    build_taxonomy_search_expansion,
    format_topic_taxonomy_report,
    list_controlled_topics,
    resolve_controlled_topic_label,
    save_controlled_topic,
)
from .taxonomy_topic_search import (
    build_taxonomy_topic_search_plan,
    format_taxonomy_topic_search_report,
    get_taxonomy_topic_search_health,
    resolve_taxonomy_search_query,
    search_taxonomy_aware_topic_content,
)
from .locator_migration_planner import (
    audit_document_locator_contracts,
    build_locator_migration_plan,
    format_locator_migration_report,
    load_locator_migration_plan,
    preview_locator_correction,
)
from .locator_migration_execution import (
    execute_locator_migration_proposal,
    format_locator_migration_execution_report,
    load_locator_migration_execution_receipt,
    rollback_locator_migration_execution,
    validate_locator_migration_execution,
)
from .source_workflow_coordinator import (
    calculate_pipeline_state_fingerprint,
    create_source_workflow_plan,
    execute_source_workflow_stage,
    format_source_workflow_report,
    get_source_workflow_resume_state,
    recommend_next_source_workflow_stage,
)
from .document_structure import analyze_chunk_quality, build_document_structure_map, detect_document_headings, detect_footnotes_and_references, detect_possible_figures, detect_possible_tables, detect_repeated_headers_footers, detect_toc_candidates, get_document_structure_summary, load_document_structure_map, normalize_extracted_page_text, recommend_rechunk_plan
from .config_manager import load_project_config
from .governance.dependencies import validate_dependencies as validate_feature_dependencies
from .governance.docs_coverage import get_docs_coverage
from .governance.extensions import get_extension_registry
from .governance.performance_budget import get_performance_budget_status
from .governance.project_health import get_project_health
from .governance.release_gates import run_release_gate
from .governance.roadmap_registry import load_roadmap_registry, summarize_roadmap_status as summarize_roadmap
from .governance.workflow_audit import run_workflow_audit
from .objective_packs import load_objective_pack
from .proposal_review import add_proposal_review_note, apply_proposal_review_ui_action, calculate_promotion_readiness, copy_proposal_review_summary, detect_duplicate_proposals, detect_proposal_conflicts, get_proposal_review_summary, get_proposal_review_ui_state, list_proposal_review_queue, load_proposal_review, score_citation_strength, select_proposal_for_review_ui, update_proposal_review_status
from .reliability.historical_replay import run_historical_replay
from .reliability.loading import load_audit_snapshot_tolerant
from .reliability.storage import save_audit_snapshot
from .search_profiles import load_search_profile, save_search_profile
from .source_impact_analysis import (
    analyze_source_change_impact,
    create_source_revalidation_item,
    find_source_dependencies,
    format_source_impact_report_text,
    list_source_revalidation_queue,
    update_source_revalidation_status,
)
from .source_revalidation_review import (
    build_revalidation_evidence_recheck,
    build_revalidation_review_workspace,
    finalize_source_revalidation_review,
    format_source_revalidation_resolution_report,
    list_source_revalidation_resolutions,
    load_source_revalidation_resolution,
)

from .corpus_execution_recovery import (
    acquire_corpus_batch_lock,
    build_corpus_repair_plan,
    build_execution_idempotency_key,
    build_partial_write_recovery_plan,
    cancel_corpus_batch_plan,
    clear_stale_corpus_batch_lock,
    create_corpus_repair_backup,
    detect_partial_corpus_writes,
    detect_stale_corpus_batch_lock,
    detect_stale_executions,
    execute_corpus_repair_plan,
    format_corpus_execution_report_text,
    format_corpus_integrity_report_text,
    get_batch_recovery_state,
    get_corpus_batch_lock,
    get_corpus_execution_config,
    get_corpus_execution_history,
    get_corpus_index_registry,
    list_execution_receipts,
    list_quarantined_corpus_records,
    load_corpus_checkpoint,
    load_execution_receipt,
    pause_corpus_batch_plan,
    release_corpus_batch_lock,
    resume_corpus_batch_plan,
    rollback_corpus_repair,
    validate_batch_action_dependencies,
    validate_corpus_checkpoint,
    validate_corpus_execution_config,
    validate_corpus_index_integrity,
    validate_single_index_integrity,
    verify_corpus_repair_backup,
)
from .source_corpus_manager import build_source_corpus_inventory, bulk_recalculate_source_reliability, bulk_refresh_evidence_binders, create_corpus_batch_plan, create_retry_batch_for_failed_sources, detect_corpus_missing_steps, detect_source_missing_steps, execute_corpus_batch_plan, format_source_corpus_report_text, get_source_corpus_health, list_corpus_batch_plans, list_duplicate_source_queue, list_failed_source_tasks, list_superseded_source_queue, load_corpus_batch_plan, load_source_corpus_inventory
from .source_document_reader import build_citation_snippet, build_page_diagnostics, copy_snippet_from_selected_result, create_citation_from_search_result, create_citation_from_selected_result, create_proposal_from_search_result, create_proposal_from_selected_result, get_document_chunk_text, get_document_page_text, get_document_reader_state, get_page_diagnostic_summary, get_search_result_context, get_search_ui_state, get_source_search_health, list_document_chunks, load_page_diagnostics, mark_search_result_feedback, mark_selected_result_feedback, run_document_search_for_ui, search_document, select_search_result_for_ui
from .source_documents import extract_pdf_text, get_extracted_text, list_source_documents, load_source_document, register_pdf_source
from .source_reliability_manager import calculate_source_staleness, detect_duplicate_source_identity, format_source_reliability_report_text, get_source_quality_dashboard, get_source_relationships, link_source_replacement, list_evidence_binders_using_source, load_source_reliability_history, recalculate_source_reliability, refresh_evidence_binders_for_source, update_source_metadata_for_reliability
from .source_knowledge import chunk_extracted_text as chunk_source_document, create_manual_proposal as create_manual_source_proposal, create_source_citation, get_source_knowledge_health, list_source_proposals, search_source_chunks, update_proposal_status as update_source_proposal_status
from .watchlists import run_watchlist_scan


def analyze_election(*args, **kwargs) -> dict[str, object]:
    return build_snapshot(*args, **kwargs)


def search_windows(*args, **kwargs) -> dict[str, object]:
    return build_election_report(*args, **kwargs)


def run_fast_lane(candidate: Mapping[str, object]) -> dict[str, object]:
    tactical = build_tactical_analysis_report(candidate)
    return tactical.fast_lane.to_json()


def load_audit_snapshot(path: Path | str) -> dict[str, object]:
    return load_audit_snapshot_tolerant(path)


__all__ = [
    "analyze_election",
    "backup_reliability_data",
    "load_audit_snapshot",
    "load_objective_pack",
    "load_source_document",
    "load_search_profile",
    "list_source_documents",
    "restore_reliability_data",
    "run_fast_lane",
    "run_historical_replay",
    "run_watchlist_scan",
    "save_audit_snapshot",
    "save_search_profile",
    "search_windows",
    "extract_pdf_text",
    "get_extracted_text",
    "register_pdf_source",
    "chunk_source_document",
    "search_source_chunks",
    "create_manual_source_proposal",
    "list_source_proposals",
    "update_source_proposal_status",
    "create_source_citation",
    "get_source_knowledge_health",
    "load_roadmap_registry",
    "summarize_roadmap",
    "validate_feature_dependencies",
    "get_project_health",
    "run_release_gate",
    "run_workflow_audit",
    "load_project_config",
    "get_extension_registry",
    "get_docs_coverage",
    "get_performance_budget_status",
    "run_document_preflight",
    "load_document_preflight",
    "list_document_preflights",
    "get_document_preflight_summary",
    "can_extract_after_preflight",
    "format_preflight_report_text",
    "build_page_diagnostics",
    "load_page_diagnostics",
    "get_page_diagnostic_summary",
    "get_document_reader_state",
    "get_document_page_text",
    "get_document_chunk_text",
    "list_document_chunks",
    "search_document",
    "get_search_result_context",
    "create_proposal_from_search_result",
    "create_citation_from_search_result",
    "mark_search_result_feedback",
    "build_citation_snippet",
    "get_source_search_health",
    "normalize_extracted_page_text",
    "detect_repeated_headers_footers",
    "detect_document_headings",
    "detect_toc_candidates",
    "detect_possible_tables",
    "detect_possible_figures",
    "detect_footnotes_and_references",
    "build_document_structure_map",
    "load_document_structure_map",
    "get_document_structure_summary",
    "analyze_chunk_quality",
    "recommend_rechunk_plan",
    "score_citation_strength",
    "get_proposal_review_summary",
    "detect_duplicate_proposals",
    "detect_proposal_conflicts",
    "update_proposal_review_status",
    "add_proposal_review_note",
    "calculate_promotion_readiness",
    "list_proposal_review_queue",
    "load_proposal_review",
    "get_proposal_review_ui_state",
    "select_proposal_for_review_ui",
    "copy_proposal_review_summary",
    "apply_proposal_review_ui_action",
    "group_citations_for_proposal",
    "get_or_create_source_reliability",
    "update_source_reliability_metadata",
    "score_citation_bundle_strength",
    "detect_cross_document_support",
    "detect_cross_document_conflicts",
    "calculate_evidence_coverage",
    "detect_weak_or_stale_sources",
    "build_evidence_binder",
    "load_evidence_binder",
    "get_evidence_binder_summary",
    "format_evidence_binder_report_text",
    "update_source_metadata_for_reliability",
    "recalculate_source_reliability",
    "calculate_source_staleness",
    "link_source_replacement",
    "get_source_relationships",
    "detect_duplicate_source_identity",
    "get_source_quality_dashboard",
    "refresh_evidence_binders_for_source",
    "list_evidence_binders_using_source",
    "format_source_reliability_report_text",
    "load_source_reliability_history",
    "format_source_corpus_report_text",
    "list_superseded_source_queue",
    "list_duplicate_source_queue",
    "bulk_refresh_evidence_binders",
    "bulk_recalculate_source_reliability",
    "create_retry_batch_for_failed_sources",
    "list_failed_source_tasks",
    "execute_corpus_batch_plan",
    "list_corpus_batch_plans",
    "load_corpus_batch_plan",
    "create_corpus_batch_plan",
    "get_source_corpus_health",
    "detect_corpus_missing_steps",
    "detect_source_missing_steps",
    "load_source_corpus_inventory",
    "build_source_corpus_inventory",
    "get_corpus_execution_config",
    "validate_corpus_execution_config",
    "acquire_corpus_batch_lock",
    "release_corpus_batch_lock",
    "detect_stale_corpus_batch_lock",
    "get_corpus_batch_lock",
    "load_execution_receipt",
    "list_execution_receipts",
    "validate_batch_action_dependencies",
    "build_execution_idempotency_key",
    "load_corpus_checkpoint",
    "validate_corpus_checkpoint",
    "resume_corpus_batch_plan",
    "pause_corpus_batch_plan",
    "cancel_corpus_batch_plan",
    "get_batch_recovery_state",
    "detect_stale_executions",
    "get_corpus_execution_history",
    "format_corpus_execution_report_text",
    "get_corpus_index_registry",
    "validate_corpus_index_integrity",
    "validate_single_index_integrity",
    "build_corpus_repair_plan",
    "create_corpus_repair_backup",
    "verify_corpus_repair_backup",
    "execute_corpus_repair_plan",
    "rollback_corpus_repair",
    "list_quarantined_corpus_records",
    "detect_partial_corpus_writes",
    "build_partial_write_recovery_plan",
    "format_corpus_integrity_report_text",
    "analyze_source_change_impact",
    "find_source_dependencies",
    "create_source_revalidation_item",
    "list_source_revalidation_queue",
    "update_source_revalidation_status",
    "format_source_impact_report_text",
    "build_revalidation_review_workspace",
    "build_revalidation_evidence_recheck",
    "finalize_source_revalidation_review",
    "load_source_revalidation_resolution",
    "list_source_revalidation_resolutions",
    "format_source_revalidation_resolution_report",
    "build_document_manifest",
    "load_document_manifest",
    "validate_source_locator",
    "reconcile_document_subsystems",
    "get_document_backend_readiness",
    "format_document_manifest_report",
    "calculate_pipeline_state_fingerprint",
    "recommend_next_source_workflow_stage",
    "create_source_workflow_plan",
    "execute_source_workflow_stage",
    "get_source_workflow_resume_state",
    "format_source_workflow_report",
    "build_document_scoped_fingerprint",
    "build_document_content_map",
    "find_related_document_content",
    "validate_document_provenance_contract",
    "get_reader_backend_readiness",
    "format_document_content_map_report",
    "build_document_content_curation_workspace",
    "validate_content_curation_change",
    "save_document_content_curation_change",
    "build_curated_document_content_map",
    "load_document_content_curation",
    "get_document_content_curation_readiness",
    "get_document_content_curation_summary",
    "format_document_content_curation_report",
    "list_document_content_curation_revisions",
    "load_document_content_curation_revision",
    "compare_document_content_curation_revisions",
    "validate_historical_curation_revision",
    "restore_document_content_curation_revision",
    "format_document_content_curation_history_report",
    "format_document_content_curation_comparison_report",
    "format_document_content_curation_restore_report",
    "create_rebase_workspace_from_current_stale_curation",
    "create_rebase_workspace_from_historical_revision",
    "load_document_content_rebase_workspace",
    "list_document_content_rebase_workspaces",
    "refresh_document_content_rebase_conflicts",
    "apply_document_content_rebase_resolution",
    "get_document_content_rebase_readiness",
    "build_document_content_rebase_proposed_overlay",
    "commit_document_content_rebase_workspace",
    "abandon_document_content_rebase_workspace",
    "format_document_content_rebase_report",
    "create_document_content_bulk_plan",
    "load_document_content_bulk_plan",
    "list_document_content_bulk_plans",
    "add_document_content_bulk_operation",
    "remove_document_content_bulk_operation",
    "replace_document_content_bulk_operation",
    "clear_document_content_bulk_operations",
    "preview_document_content_bulk_plan",
    "validate_document_content_bulk_plan",
    "list_document_content_bulk_review_queue",
    "approve_document_content_bulk_plan",
    "reject_document_content_bulk_plan",
    "refresh_document_content_bulk_plan",
    "commit_document_content_bulk_plan",
    "format_document_content_bulk_report",
    "load_document_content_transaction",
    "list_document_content_transactions",
    "get_document_content_transaction_status",
    "abandon_document_content_transaction",
    "scan_document_content_integrity",
    "create_document_content_recovery_plan",
    "load_document_content_recovery_plan",
    "apply_document_content_recovery_plan",
    "rebuild_document_content_indexes",
    "format_document_content_transaction_report",
    "format_document_content_integrity_report",
    "format_document_content_recovery_report",
    "build_backend_contract_validation_plan",
    "run_backend_contract_validation",
    "load_backend_contract_validation",
    "get_backend_contract_validation_health",
    "format_backend_contract_validation_report",
    "create_pdf_viewport_session",
    "render_pdf_viewport_page",
    "navigate_pdf_viewport",
    "synchronize_pdf_viewport_to_locator",
    "format_pdf_viewport_report",
    "extract_pdf_page_text_layer",
    "map_pdf_locator_to_rectangles",
    "build_pdf_highlight_overlay",
    "select_pdf_text_in_rectangle",
    "format_pdf_text_layer_report",
    "create_pdf_reader_workspace",
    "save_pdf_reader_bookmark",
    "save_pdf_reader_annotation",
    "draft_citation_from_pdf_selection",
    "format_pdf_reader_workspace_report",
    "build_citation_draft_review_workspace",
    "save_citation_draft_review_decision",
    "create_citation_from_approved_draft",
    "get_citation_draft_review_health",
    "format_citation_draft_review_report",
    "build_evidence_handoff_review_workspace",
    "save_evidence_handoff_review_decision",
    "insert_handoff_citation_into_binder",
    "create_proposal_draft_from_evidence_handoff",
    "format_evidence_handoff_review_report",
    "build_proposal_promotion_workspace",
    "save_proposal_promotion_decision",
    "promote_approved_proposal",
    "get_proposal_promotion_health",
    "format_proposal_promotion_report",
    "build_proposal_rule_activation_workspace",
    "save_proposal_rule_activation_decision",
    "activate_rule_from_promoted_proposal",
    "rollback_proposal_rule_activation",
    "format_proposal_rule_activation_report",
    "build_rule_activation_revalidation_workspace",
    "run_rule_runtime_contract_validation",
    "save_rule_activation_revalidation_decision",
    "complete_rule_activation_revalidation",
    "format_rule_activation_revalidation_report",
    "save_controlled_topic",
    "list_controlled_topics",
    "resolve_controlled_topic_label",
    "build_taxonomy_search_expansion",
    "format_topic_taxonomy_report",
    "resolve_taxonomy_search_query",
    "build_taxonomy_topic_search_plan",
    "search_taxonomy_aware_topic_content",
    "get_taxonomy_topic_search_health",
    "format_taxonomy_topic_search_report",
    "audit_document_locator_contracts",
    "build_locator_migration_plan",
    "load_locator_migration_plan",
    "preview_locator_correction",
    "format_locator_migration_report",
    "validate_locator_migration_execution",
    "execute_locator_migration_proposal",
    "load_locator_migration_execution_receipt",
    "rollback_locator_migration_execution",
    "format_locator_migration_execution_report",
]






